Remove is_allowed_to_start
sublimelsp/LSP-tailwindcss pull request #14
Opened 2021-06-30 16:13 UTC by predragnikolic

As it doesn't allow the server to initialize if the tailwind.config.js is in a sub directory.

2021-06-30 21:25 UTC, rchl commented
But it triggers errors like:

```
Traceback (most recent call last):
  File "/me/Sublime Text/Packages/LSP/plugin/session_view.py", line 172, in on_capability_added_async
    self._register_auto_complete_triggers(registration_id, trigger_chars or [])
  File "/me/Sublime Text/Packages/LSP/plugin/session_view.py", line 96, in _register_auto_complete_triggers
    self._apply_auto_complete_triggers(self.view.settings(), trigger_chars, registration_id)
  File "/me/Sublime Text/Packages/LSP/plugin/session_view.py", line 130, in _apply_auto_complete_triggers
    trigger["characters"] = "".join(trigger_chars)
TypeError: sequence item 8: expected str instance, NoneType found
```

when there is no config file.

Have you checked what the server actually supports and whether we should maybe replicate that? Where does it search for the config if not only in the root? Is it relative to the opened file?

2021-07-01 00:09 UTC, predragnikolic commented
You are right.

We should probably replicate what the vs code extension does - https://github.com/tailwindlabs/tailwindcss-intellisense/blob/766a5d533dcb68640ce6b3270488f6701dd1173d/packages/vscode-tailwindcss/src/extension.ts#L378

2021-07-01 00:18 UTC, predragnikolic commented
I could use wcmatch dependency to find the config file in the sub folder https://facelessuser.github.io/wcmatch/glob/

2021-07-09 20:39 UTC, rwols commented
The glob is so simple, why not use `os.walk` and check for each file if it’s a filename of interest? No need for dependencies then.

2021-07-13 19:37 UTC, predragnikolic commented
Thanks for suggesting `os.walk`

2021-07-13 20:05 UTC, rwols commented on plugin.py
> +                directories[:] = [d for d in directories if not re.search(folder_excldue_pattern, d)]
This is a bit odd. the folder_exclude_pattern is a glob, but we're using it as if it's a regex.

2021-07-13 20:06 UTC, rchl requested changes

2021-07-13 20:06 UTC, rchl commented on plugin.py
> +                directories[:] = [d for d in directories if not re.search(folder_excldue_pattern, d)]
The exclude pattern is not a regexp so using `re.search` is not correct. If you want to handle wildcards in the pattern then you'd need something more sophisticated. If not handling wildcards is OK then just checking if exists in the list would maybe suffice.

2021-07-13 20:06 UTC, rchl commented on plugin.py
> +        folder_exclude_patterns.append('node_modules') # definitely exclude node_modules
Converting to `Set` would result in faster lookup and avoid potential duplicates.

2021-07-13 20:06 UTC, rchl commented on plugin.py
> +        config_file_pattern = '(tailwind|tailwind.config).(js|cjs)'
The dots need to be escaped.
And there could be a `$` at the end.

2021-07-13 20:49 UTC, predragnikolic commented
Sublime supports https://www.sublimetext.com/docs/file_patterns.html just `*` and `?` file patterns which luckily fnmatch supports :)

2021-07-13 20:52 UTC, rchl commented on plugin.py
> +        for folder_excldue_pattern in folder_exclude_patterns or []:
```suggestion
        for folder_exclude_pattern in folder_exclude_patterns or []:
```

2021-07-13 20:52 UTC, rchl commented on plugin.py
> +            if re.search(file_pattern, file):
`re.match` should be a better fit in this case.

2021-07-13 20:52 UTC, rchl approved these changes

2021-07-13 21:50 UTC, rchl commented
> Sublime supports [sublimetext.com/docs/file_patterns.html](https://www.sublimetext.com/docs/file_patterns.html) just `*` and `?` file patterns which luckily fnmatch supports :)

Those are not entirely equivalent because handling of forward-slashes is different. In ST `*` doesn't match across those but it does in `fnmatch` (mainly because `fnmatch` is supposed to be used to match file names only).

2021-07-14 18:43 UTC, merged

2021-07-14 18:47 UTC, predragnikolic commented
> Those are not entirely equivalent because handling of forward-slashes is different. In ST * doesn't match across those but it does in fnmatch (mainly because fnmatch is supposed to be used to match file names only).

If the fnmatch causes some unexpected issues with folder_exclude_patterns. I will switch from patters to regular strings
```
directories[:] = [d for d in directories if d not in ['node_modules', '.git']] 
```